### ISSUE TITLE
MLA Complaints

### ISSUE THREAD

**Issue by varmab** [varmab/stellenthyd#2]
Any authenticated user of website need to be able to submit complaint that will be saved in the database and sent to all emails of concerned complaint contacts (Becareful, Don't send to real data of contacts during development).

**Comment by lakshmipathiraju1** [comment]
[https://app.zenhub.com/files/195219777/5ca50d87-6505-4922-8d5b-4fc46fed9255/download](https://app.zenhub.com/files/195219777/5ca50d87-6505-4922-8d5b-4fc46fed9255/download)
