### ISSUE TITLE
Vue/Quasar/Backend . --Learning

### ISSUE THREAD

**Issue by MadhaviBrc** [varmab/stellenthyd#27]

**Comment by kashi-mamidisetti** [comment]
Today I read about
1) what is Vue js
2) what is the difference b/w the react js and Vue js
3) How to create an instance in Vue
4) How to use v-directives
	i.e a) v-on
	    b) v-click
	    c) v-bind
	    d) v-model
	    e) v-for
	    f) v-if and v-else
	    g) v-show ..etc
5) How to define data and methods in Vue js
