### ISSUE TITLE
Encryption integration

### ISSUE THREAD

**Issue by MadhaviBrc** [varmab/stellenthyd#32]

**Comment by pavankumardasireddy** [comment]
Implemented encryption of connection string on react project and decrypting on vuejs project on local machine.

**Comment by pavankumardasireddy** [comment]
Tried integrate it on client server. But there is some login issue in client code. 
Following are the errors: 
production credentials- 
error:  ConnectionError: Login failed for user 'sacalmeddev'.
dev credentials
error:  ConnectionError: Login failed for user 'saslwebapp'.

**Comment by pavankumardasireddy** [comment]
Completed functionality of:
-- Sending user connection string and patId as URI encoded encrypted text from backend(Login API)
-- Saving connection string values in cookies of react-application
-- Fetching values from cookies when user click on App/Remider in react-application
-- Decoding and decrypting the string and prepared connection object for API calls
-- Injected vue-pat-portal application to react-application using iframe.
